name: 构建Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        pip3 install --upgrade pip
        pip3 install --upgrade Cython==0.29.33
        pip3 install --upgrade setuptools
        
    - name: 设置Java环境
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        
    - name: 安装Python依赖
      run: |
        pip3 install buildozer
        pip3 install kivy
        
    - name: 缓存Buildozer全局目录
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-${{ hashFiles('**/*.spec') }}
        
    - name: 预先接受SDK许可协议
      run: |
        mkdir -p ~/.android
        echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > ~/.android/repositories.cfg
        echo 'y' | sudo apt-get install -y android-sdk
        
    - name: 构建APK
      run: |
        # 使用简化版本文件
        cp buildozer_simple.spec buildozer.spec
        cp main_simple.py main.py
        
        # 设置环境变量
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
        
        # 预先接受所有SDK许可协议
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-googletv-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/google-gdk-license
        echo "33b6a2b64607f11b759f320ef9dff4ae5c47d97a" > $ANDROID_SDK_ROOT/licenses/mips-android-sysimage-license
        
        # 构建APK
        buildozer android debug
        
    - name: 上传APK文件
      uses: actions/upload-artifact@v3
      with:
        name: 大乐透预测系统-APK
        path: bin/*.apk
        
    - name: 显示构建信息
      run: |
        echo "构建完成！"
        ls -la bin/
        if [ -f bin/*.apk ]; then
          echo "APK文件大小："
          du -h bin/*.apk
        fi 
